name: Install terraform with tfenv
description: Sets up tfenv and terraform for the input directory.
inputs:
  directory:
    description: Directory or sub-directory of a directory with a .terraform-version file.
    required: false
    default: ./terraform
runs:
  using: composite
  steps:
    - run: |
        if tfenv --version; then
          echo "tfenv already installed, skipping"
        else
          TMPDIR=$(mktemp -d)
          git clone --depth=1 --branch v3.0.0 https://github.com/tfutils/tfenv.git $TMPDIR
          echo "$TMPDIR/bin" >> "$GITHUB_PATH"
        fi
      shell: bash

    - working-directory: ${{ inputs.directory }}
      run: TFENV_CURL_OUTPUT=0 tfenv use
      shell: bash
