name: Install terraform with tfenv
description: Sets up tfenv and terraform for the input directory.
inputs:
  directory:
    description: Directory or sub-directory of a directory with a .terraform-version file.
    required: false
    default: ./terraform
runs:
  using: composite
  steps:
    - run: |
        if ! tfenv --version; then
          git clone --depth=1 https://github.com/tfutils/tfenv.git ~/.tfenv
          echo "PATH=$HOME/.tfenv/bin:$PATH" >> "$GITHUB_ENV"
        else
          echo "Terraform already initialized, skipping install"
        fi
      shell: bash

    - working-directory: ${{ inputs.directory }}
      run: TFENV_CURL_OUTPUT=0 tfenv use
      shell: bash
