name: Build Runner EC2 Images

on:
  pull_request:
    paths:
      - .github/workflows/build-runner-images.yml
  schedule:
    # 00:00 on Monday each week
    - cron: "0 0 * * 1"
  workflow_dispatch:
    
jobs:
  build-image:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packer/github-actions-runner
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::${{ vars.RUNNER_ACCOUNT }}:role/github-to-aws-oidc
          aws-region: us-east-1

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: "latest"

      - name: Run `packer init`
        id: init
        run: packer init .

      - name: Run `packer validate`
        id: validate
        run: packer validate .

      - name: Packer Build
        id: build
        run: packer build -color=false -on-error=cleanup -var ami_account=${{ vars.AMI_ACCOUNT }} -var ami_filter=${{ vars.AMI_FILTER }} .
