name: External Services WAF IP Sets Sync

on:
  workflow_dispatch: # Allow manual trigger

permissions:
  contents: read
  id-token: write

jobs:
  external-services-waf-ip-sync:
    runs-on: self-hosted
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        app: [ab2d]
        env: [test]
    steps:
      - name: Checkout Platform Repository
        uses: actions/checkout@v4
      - name: Get AWS params
        uses: cmsgov/ab2d-bcda-dpc-platform/actions/aws-params-env-action@main
        env:
          AWS_REGION: ${{ vars.AWS_REGION }}
        with:
          params:
            OPS_GITHUB_TOKEN=/ci/github/token
      - name: Checkout Private Repository
        uses: actions/checkout@v4
        with:
          repository: CMSgov/cdap-private
          ref: 'main'
          sparse-checkout:
            ip-sets/external-services/allowed_ips.txt
          sparse-checkout-cone-mode: false
          path: ./scripts/temp
          token: ${{ env.OPS_GITHUB_TOKEN }}
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets[format('{0}_{1}_ACCOUNT', matrix.app, matrix.env)] }}:role/delegatedadmin/developer/${{ matrix.app }}-${{ matrix.env }}-github-actions
          aws-region: ${{ vars.AWS_REGION }}
      - name: Run WAF Sync Script
        working-directory: scripts
        run: bash waf-ip-set-sync-external-services.sh
        env:
          APP: ${{ matrix.app }}
          ENV: ${{ matrix.env }}