name: GitHub Actions runner images

on:
  pull_request:
    paths:
      - .github/workflows/github-actions-runner-images.yml
      - packer/github-actions-runner/**
  schedule:
    - cron: "0 0 * * 1"  # 00:00 on Monday each week
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packer/github-actions-runner
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-packer@v2.0.1
      - uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::${{ secrets.BCDA_ACCOUNT }}:role/delegatedadmin/developer/bcda-mgmt-github-actions
          aws-region: ${{ vars.AWS_REGION }}
      - uses: cmsgov/ab2d-bcda-dpc-platform/actions/aws-params-env-action@main
        with:
          params: |
            PKR_VAR_ami_account=/gold-image/account
            PKR_VAR_s3_tarball=/github-runner/s3-tarball
            PKR_VAR_vpc_id=/github-runner/vpc
            PKR_VAR_subnet_id=/github-runner/subnet
      - env:
          PACKER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          packer init .
          packer validate -evaluate-datasources .
          ${RUNNER_DEBUG:+"PACKER_LOG=1"} packer build .
