name: Terraform plan for github-actions-deploy-role

on:
  pull_request:
    paths:
      - .github/workflows/github-actions-deploy-role-plan.yml
      - terraform/services/github-actions-deploy-role/**
  workflow_dispatch: # Allow manual trigger

jobs:
  check-terraform-fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./actions/setup-tfenv-terraform
      - run: terraform fmt -check -diff -recursive terraform/services/github-actions-deploy-role

  terraform-plan:
    needs: check-terraform-fmt
    permissions:
      contents: read
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        app: [ab2d, bcda, dpc]
        env: [dev, test, sbx, prod]
        include:
          - app: bcda
            env: mgmt
    uses: ./.github/workflows/terraform-command.yml
    with:
      app: ${{ matrix.app }}
      env: ${{ matrix.env }}
      dir: ./terraform/services/github-actions-deploy-role
      cmd: plan
