name: Terraform apply for github-actions-oidc-provider

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/github-actions-oidc-provider-apply.yml
      - terraform/services/github-actions-oidc-provider/**
  workflow_dispatch: # Allow manual trigger

jobs:
  terraform-apply:
    permissions:
      contents: read
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        app: [ab2d]
        env: [dev, test, sbx, prod]
        include:
          - app: bcda
            env: mgmt
    uses: ./.github/workflows/terraform-command.yml
    with:
      app: ${{ matrix.app }}
      env: ${{ matrix.env }}
      dir: ./terraform/services/github-actions-oidc-provider
      cmd: apply -auto-approve
