name: Terraform apply for opt-out-import

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/opt-out-import-apply.yml
      - terraform/services/opt-out-import/**
  workflow_dispatch: # Allow manual trigger

jobs:
  terraform-apply:
    permissions:
      contents: read
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        app: [ab2d, bcda, dpc]
        env: [dev, test, sbx, prod]
    uses: ./.github/workflows/terraform-command.yml
    with:
      app: ${{ matrix.app }}
      env: ${{ matrix.env }}
      dir: ./terraform/services/opt-out-import
      cmd: apply -auto-approve
