name: Terraform plan for opt-out-import

on:
  pull_request:
    paths:
      - .github/workflows/opt-out-import-plan.yml
      - terraform/services/opt-out-import/**
  workflow_dispatch: # Allow manual trigger

jobs:
  check-terraform-fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./actions/setup-tfenv-terraform
      - run: terraform fmt -check -diff -recursive terraform/services/opt-out-import

  terraform-plan:
    needs: check-terraform-fmt
    permissions:
      contents: read
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        app: [ab2d, bcda, dpc]
        env: [dev, test, sbx, prod]
    uses: ./.github/workflows/tf-cmd.yml@main
    with:
      app: ${{ matrix.app }}
      env: ${{ matrix.env }}
      dir: ./terraform/services/opt-out-import
      cmd: plan
