name: Terraform Apply

on:
  push:
    branches:
      - main
    paths:
      - 'terraform/services/github-actions/**' # Specify the path to trigger the workflow
  workflow_dispatch: # Allow manual trigger

permissions:
    id-token: write   # This is required for requesting the JWT
    contents: read    # This is required for actions/checkout

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::755619740999:role/github-to-aws-oidc 
          aws-region: us-east-1

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform initn

      - name: Terraform Apply
        run: terraform apply -auto-approve
