name: Terraform Plan

on:
  workflow_call:
    inputs:
      directory:
        description: The directory in which init and plan will be run.
        required: true
        type: string
      role:
        description: The AWS IAM role to run as via OIDC.
        required: true
        type: string
      backends:
        description: Space-separated backend configuration files.
        required: true
        type: string
      tf-vars:
        description: Space-separated variables for terraform plan.
        required: true
        type: string

permissions:
  contents: read # Required for actions/checkout
  id-token: write # Required for requesting the JWT for OIDC

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.directory }}

    steps:
      - uses: actions/checkout@v4

      - uses: ./actions/setup-tfenv-terraform

      - uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ inputs.role }}
          aws-region: us-east-1

      - name: Terraform init
        run: |
          backends="-backend-config=${{ github.workspace }}/$(echo '${{ inputs.backends }}' | sed -E 's|[[:space:]]+| -backend-config=${{ github.workspace }}|g')"
          terraform init -reconfigure $backends

      - name: Terraform plan
        run: |
          tf_vars="-var $(echo '${{ inputs.tf-vars }}' | sed -E 's/[[:space:]]+/ -var /g')"
          terraform plan $tf_vars
