name: Terraform apply for tfstate

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/tfstate-apply.yml
      - terraform/services/tfstate/**
  workflow_dispatch: # Allow manual trigger

jobs:
  terraform-apply:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform/services/tfstate
    strategy:
      matrix:
        app: [ab2d, bcda, dpc]
        env: [dev, test, sbx, prod]
        include:
          - app: bcda
            env: mgmt
    environment: ${{ matrix.app }}-${{ matrix.env }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./actions/setup-tfenv-terraform
      - uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ vars.DEPLOY_ROLE }}
          aws-region: ${{ vars.AWS_REGION }}
      - run: terraform init -backend-config=../../backends/${{ matrix.app }}-${{ matrix.env }}.s3.tfbackend
      - run: terraform apply -auto-approve
        env:
          TF_VAR_name: ${{ matrix.app }}-${{ matrix.env }}-tfstate
